### ISSUE TITLE
Fix chat breaking

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#139]
### Task Description
http://pw-phoenix.com/forum/index.php?/topic/18703-chat-sanitization/
### Specification/Explicit TODO
It can be broken in local, faction and admin chat by typing the following marks:
^^^^^^^
The ^ sign basically causes the chat to skip a line. This doesn't work in global chat for some reason.

**Comment by Thomas-Smyth** [comment]
Not sure what effect this will have on the module, as `^` is used in some of the PW scripts to break lines.

**Comment by Thomas-Smyth** [comment]
Done in server scripts.
