### ISSUE TITLE
Dog companion

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#152]
### Task Description
Implement a dog model & animation
### Specification/Explicit TODO
First we need to get a model of the dog. One can be taken from here:
https://forums.taleworlds.com/index.php/topic,271193.0.html
Or we can ask Exima to model a dog.

Then animations need to be added for the dog. Just running basically, no attacks.

Then, if possible implement a script that enables the dog to follow you. Apparently, Kingsman already has that in his script. To be discussed. The follow script is also in feudal world if I am not mistaken.
### Additional
This would be used in roleplay servers.

**Comment by WilliamPhoenix** [comment]
This would be used in roleplay servers.

**Comment by Saptortacus** [comment]
What is the current progress with this?

**Comment by Thomas-Smyth** [comment]
@Saptortacus a model has found, but not sure how good it is though. I think it will be best to leave the scripts out for now as I do not know how CRP, who this is intended for, wish for dogs to be made accessible, etc.

**Comment by WilliamPhoenix** [comment]
Merged without the script. Just the dog module.
