### ISSUE TITLE
Arrow cart

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#155]
### Task Description
Arrow cart
### Specification/Explicit TODO
Create a cart that will accept arrows. Discuss the idea behind it.
https://github.com/SmartPhoenix/PWMod/issues/151

**Comment by Saptortacus** [comment]
Gib textures

**Comment by Thomas-Smyth** [comment]
The scripts for limiting only arrows to this cart are already added. Just need the model and textures for this and update the scene prop that I have already added as a template.

**Comment by Thomas-Smyth** [comment]
https://github.com/SmartPhoenix/Persistent-Kingdoms/issues/182
