### ISSUE TITLE
Open/Close Helmet

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#167]
### Task Description
Open/Close Helmet
### Specification/Explicit TODO
We have multiple helmets that have an opened and closed variation. When we finally finish with all of them we'll try to implement the following script which enables you to open and close the helmet:
https://forums.taleworlds.com/index.php/topic,166488.0.html

Probably best to include it into the "C" menu.

**Comment by Thomas-Smyth** [comment]
Script has been added. You will need to add the togglable helmet variants when they are added to the mod, I can explain how to do this on TS.

**Comment by Thomas-Smyth** [comment]
Integrated into the armour development branch. Watch https://github.com/SmartPhoenix/Persistent-Kingdoms/issues/20 for merge into integration.
