### ISSUE TITLE
Add sitting animation

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#214]
### Task Description
Add sitting animation
### Specification/Explicit TODO
Two separate animations should be added. One for sitting on chairs (which probably has to be binded to scene props) and another for sitting anywhere (which should basically be an animation in the menu that you can click)

**Comment by Saptortacus** [comment]
@WilliamPhoenix @Tommy
Please provide the necessary sources to me so I can begin to work with this.

**Comment by Thomas-Smyth** [comment]
@Saptortacus probably best if I implement this. I have all the code and resources for it, so it will be easier for me to do than to explain it to you.

**Comment by WilliamPhoenix** [comment]
Native chairs:
chair_trunk_a
chair_trunk_b
chair_trunk_c
chair_castle_a
tavern_chair_a
tavern_chair_b
gothic_chair
chair_trestle

**Comment by Thomas-Smyth** [comment]
Added, just need testing to ensure the player position is correct.
