### ISSUE TITLE
Closed Testing Topics

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#239]
### Task Description
Closed Testing Topics
#### Group 1: William&Dekkers&Bridge Troll&Exima
- Launcher functionality
- Banners
- Healer class change
- Dismounted knight & mounted knight (and other class changes)
- New armours (Open/close helmet)
- New weapons (one-handed, two-handed, spears!)
- New scene props (collisions, textures)
- New trees & flora kinds (collisions, textures, cutting)
#### Group 2: Tommy&Saptor&Pain
- Test the music items (lute, lyre, horn)
- Log system (Pay attention to all implementations & what is missing)
- Spectator system
- Poll yourself lord
- Marshal feature
- Sync when lord relogs (keys)
- Commit suicide
- Castle capture animation
- Join commoners revertable
- Faster item transfer
- Timer after a poll fails/succeeds
- Increased offset for bought items
- Drop all button
- Kicked/outlawed messages
- Key messages
- Basic name labels
- Show pouch to all players in the area
- Simple show pouch process
- Arrow holders
- Lockpicked message
- Mute all admin option
### Caution with
Everything
### Additional
Have fun.

**Comment by WilliamPhoenix** [comment]
Testers: Hero, OldPilgrim, Michael, Otto, Julia, ?
Group 1:
Group 2:

**Comment by WilliamPhoenix** [comment]
Bugs & Fixes:
Roof textures from French walls look like plastic.

**Comment by LuisEngelniederhammer** [comment]
Linked issue: https://github.com/SmartPhoenix/Persistent-Kingdoms/issues/238

**Comment by LuisEngelniederhammer** [comment]
#238

**Comment by Saptortacus** [comment]
Music: Wearable with shields

**Comment by Saptortacus** [comment]
Logs:

- Says the person hit himself with a fist when he falls down

**Comment by WilliamPhoenix** [comment]
Issues made. Good test.
