### ISSUE TITLE
Special/strange weapons

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#242]
### Task Description
Special/strange weapons
### Specification/Explicit TODO
Have a look at more weapons that are special or strange that could be implemented into the mod via different channels. They can be slightly better than other weapons but ridiculously expensive.

**Comment by Thomas-Smyth** [comment]
Pull them from a rock?

**Comment by WilliamPhoenix** [comment]
Added 7 weapons (royal, special).
