### ISSUE TITLE
Script Errors

### ISSUE THREAD

**Issue by Saptortacus** [SmartPhoenix/Persistent-Kingdoms#267]
Server Console:
- player_adjust_gold. At script: player_adjust_gold. At script: player_adjust_gold. SCRIPT WARNING ON OPCODE 406: Invalid Player ID: -1; LINE NO: 24: ||| When people use money pouches, or when they die?

Client:
- SCRIPT WARNING ON OPCODE 528: Invalid Player ID: 24; LINE NO: 20: At Missiton Template mst_conquest trigger no: 5 consequences ||| When a player logs in

**Comment by Thomas-Smyth** [comment]
These in integration?

**Comment by Saptortacus** [comment]
Yes

**Comment by Saptortacus** [comment]
When I killed an admin horse:
 SCRIPT WARNING ON OPCODE 407: Invalid Player ID: -1; LINE NO: 4:
 At script: player_drop_loot. SCRIPT WARNING ON OPCODE 407: Invalid Player ID: -1; LINE NO: 8:
 At script: player_adjust_gold. At script: player_adjust_gold. SCRIPT WARNING ON OPCODE 408: Invalid Player ID: -1; LINE NO: 22:
 At script: player_adjust_gold. At script: player_adjust_gold. SCRIPT WARNING ON OPCODE 395: Invalid Player ID: -1; LINE NO: 25:
 At script: player_adjust_gold. At script: player_adjust_gold. At script: player_adjust_gold. At script: player_adjust_gold. SCRIPT WARNING ON OPCODE 406: Invalid Player ID: -1; LINE NO: 24:
 At script: player_drop_loot. SCRIPT WARNING ON OPCODE 1710: Invalid Agent ID: 0; LINE NO: 25:
 At script: player_drop_loot.

**Comment by Thomas-Smyth** [comment]
I think I solved that once before. Must have been in a branch that didn't get merged. Will take a look at it later.

**Comment by Thomas-Smyth** [comment]
Fix the one where you kill a non human agent, such a horse.

I cannot replicate the other two.

**Comment by Thomas-Smyth** [comment]
Closing this as most of these were fixed. Please make separate issues if they reoccur.
