### ISSUE TITLE
Optimisation System [Bridge Troll]

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#36]
Optimisation System [Bridge Troll]

**Comment by SaptorPhoenix** [comment]
There are some triggers in module_mission_template.py file that runs with an interval. An example for such triggers is the herd controlling trigger. If we can increase the interval of some triggers considering its cost, it will help increase the performance of server.

**Comment by LuisEngelniederhammer** [comment]
@SaptorPhoenix this is about an actual system that is linked to the pw netcode which should reduce performance cost. I also don't know how increasing the interval of condition checking within a trigger would increase performance, it would cause the opposite most likely. However if there is something that can be done, new Task and Branch please 🗡

**Comment by BNSMarko** [comment]
He probably meant decreasing the interval by increasing the necessary tick time.

**Comment by Saptortacus** [comment]
@BNSMarko the opposite lol

**Comment by Thomas-Smyth** [comment]
Gonna close this for now as it's got a too broad scope.

Issues about adjusting loop intervals have been made.
