### ISSUE TITLE
Remove projectiles from capture points

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#369]
### Task Description
Remove projectiles from capture points
### Specification/Explicit TODO
Remove projectiles from capture points

**Comment by Thomas-Smyth** [comment]
Not sure whether this will work. It seems for the operation to work the prop must be destructible.

**Comment by Saptortacus** [comment]
# Version 1.153+. Removes all missiles currently attached to the scene prop. Only works with dynamic scene props.
Perhaps not only the destructible ones.

**Comment by Saptortacus** [comment]
We can also turn them into destructible, I do not see any harm in that.

**Comment by Thomas-Smyth** [comment]
Give it ago, but I think it may give you odd behaviour. For example, it might play a sound or show a health bar.
