### ISSUE TITLE
Admin "choose" issue

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#378]
### Task Description
Admin "choose" issue
### Specification/Explicit TODO
During the test on Sunday I had to ban a person. First I teleported to person A and then clicked on "Ban player" (or whatever that is again) and it instantly banned player A instead of giving me the option to choose who to ban on the list. The list never showed up, it instantly banned player A as if he was pre-selected.

**Comment by Thomas-Smyth** [comment]
Did you have him targetted?

**Comment by Thomas-Smyth** [comment]
Could not replicate this with William. If happens again then make a new issue.
