### ISSUE TITLE
DX7 edit char screen

### ISSUE THREAD

**Issue by WilliamTheBear** [SmartPhoenix/Persistent-Kingdoms#397]
### Task Description
DX7 edit char screen
### Specification/Explicit TODO
When using DX7 and try to edit your character, the terrain behind the characters face seems bugged out. The skybox is messed up and all the trees seem to stick on the screen when rotating the camera.
Works fine on DX9.

**Comment by Thomas-Smyth** [comment]
Tried it on native?

And can you confirm skyboxes are ok in DX7 on the maps? Don't think it was tested.
