### ISSUE TITLE
Class-glitching fix

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#40]
Class-glitching fix

**Comment by SaptorPhoenix** [comment]
The glitch does not occur in vanilla PW, so it is almost certain that the glitch occurs because of the server side scripts.
Saving person's data on database when his faction changes will probably solve the problem.

**Comment by SaptorPhoenix** [comment]
Calling the function that saves the player's faction id data in the end of "cf_change_faction"
