### ISSUE TITLE
Music Bug

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/Persistent-Kingdoms#404]
### Task Description
Currently, if a player selects a song and sheath lute/lyre at the same time it allows them to play music without the lyre/lute wielded.

**Comment by DekkersNL** [comment]
Pretty sure this is also the case on NW, not entirely sure if it can be fixed unless you prevent the action entirely

**Comment by Thomas-Smyth** [comment]
Doesn't seem to be an issue currently, no one seems to be abusing it.

I think a solution is possible, but it might hurt performance, so we will leave this for now.
