### ISSUE TITLE
Hands positioned in a weird way for CWE Saracen Armors 

### ISSUE THREAD

**Issue by DekkersNL** [SmartPhoenix/Persistent-Kingdoms#409]
### Task Description
The position of the armor is probably wrong, so the hands look weird
This goes for 'medium saracen armor' 'heavy saracen armor' and  'saracen guard armor' as far as we know

### Specification/Explicit TODO
Possibly fix the position in the resource file. Not sure about the proper solution.

### Caution with
No
### Additional
Should ask Discord people

**Comment by WilliamPhoenix** [comment]
Need a modeller that will help us fix this as it's already fucked up in CWE.

**Comment by WilliamPhoenix** [comment]
Had a chat with Discord members and tried the suggested things but with no effect. We've concluded that this is such a minor thing that it will be ignored as bothering with it furthermore will be just a waste of time.
