### ISSUE TITLE
Fix the rock on the CWE tower

### ISSUE THREAD

**Issue by DekkersNL** [SmartPhoenix/Persistent-Kingdoms#435]
### Task Description
You can see through the rocks
### Specification/Explicit TODO
Not sure what the fix is (yet)
### Additional
https://steamuserimages-a.akamaihd.net/ugc/912421431247397123/FBD89C17DF06BC842CFA87DDC58CDC08D61A6A73/

**Comment by WilliamPhoenix** [comment]
Fixed! It was a wrong flag on the material.
