### ISSUE TITLE
Merge try_for_agents and try_for_players loops

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/Persistent-Kingdoms#442]
### Task Description
Merge `try_for_agents` and `try_for_players` loops

**Comment by Thomas-Smyth** [comment]
@LuisEngelniederhammer @Saptortacus 

Can you have a look at the changes I made to branch `ta-442-merge-loops`. 

I think these changes will increase performance, however, I think it may cause the same issue as with submarining where agents are not being checked enough. It seems that the time delay for the server to check each agent depends on the number of agents on the server?

**Comment by Saptortacus** [comment]
I think the game engine does not allow a trigger to run for too long, hence, the distribution of work over time is necessary.

**Comment by Thomas-Smyth** [comment]
@Saptortacus I've asked on Discord to see. Waiting for the answer.

If that's the case though, what about splitting them into separate triggers.

**Comment by Thomas-Smyth** [comment]
The scope of this issue is too big, gonna make a better issue.
