### ISSUE TITLE
Norse Armor

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/Persistent-Kingdoms#447]
### Task Description
Add more Norse armour.

http://pw-phoenix.com/forum/index.php?/topic/20461-norseviking-armors/

**Comment by WilliamPhoenix** [comment]
https://forums.taleworlds.com/index.php/topic,76333.0.html
https://forums.taleworlds.com/index.php/topic,219137.0.html
https://forums.taleworlds.com/index.php/topic,243796.0.html
https://forums.taleworlds.com/index.php/topic,275638.0.html

**Comment by WilliamPhoenix** [comment]
We decided not to add Norse armour with Dekkers.
