### ISSUE TITLE
"dropped a loot" bug

### ISSUE THREAD

**Issue by Thomas-Smyth** [SmartPhoenix/Persistent-Kingdoms#499]
```
 16:02:54 - Tommy had these items: H:-1, B:-1, G:-1, F:-1, HO:0, 1:-1, 2:-1, 3:-1, 4:-1 
 16:02:54 -  <img=ico_headshot> Tommy 
 16:02:54 - Tommy dropped a loot (IID: 2745). 
```
Incorrectly being logged on logout.

**Comment by Saptortacus** [comment]
That one is logged at setup_agent_for_respawn. In vanilla PK-PW, players do drop loot when they die. I think it is the responsibility of the server-side scripter to prevent the dropping of the loot and its logging as well.

**Comment by Thomas-Smyth** [comment]
Does gear get dropped in default PK then why you disconnect?

**Comment by Thomas-Smyth** [comment]
Only seems to occur on vanilla PK when saving scripts aren't used. Probably best not to change this behaviour as it may affect people's scripts and people using vanilla PK probably don't care that much about the logs.
