### ISSUE TITLE
Poll yourself lord if the faction is empty

### ISSUE THREAD

**Issue by DejanM4** [SmartPhoenix/Persistent-Kingdoms#51]
Make it so that you're able to poll yourself lord only and if the faction is empty.

**Comment by WilliamPhoenix** [comment]
Ok. The script works. You need 5k when polling yourself lord, can't poll yourself lord when somebody else is in faction. You still need 1k to poll other people lord. One bug: It still shows 1k instead of 5k when polling yourself lord (even though you pay 5k).

**Comment by Thomas-Smyth** [comment]
Should be fixed now.

**Comment by WilliamPhoenix** [comment]
Tested by Tommy. Works. Explanation:
You can poll yourself lord if the faction is empty. You pay 5k for it. If somebody joins the faction you can't poll yourself lord anymore. If you're lord already you can't poll yourself lord either.
