### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by WilliamTheBear** [SmartPhoenix/Persistent-Kingdoms#592]
### Task Description
Menu bug
### Specification/Explicit TODO
If I hold a weapon out and access the stationary menu and then use the key to put a weapon away, my chat will be spammed with error op codes and the chat will break for a decent amount of time.
### Additional
Not replicated yet, just reported.

**Comment by Thomas-Smyth** [comment]
Can you put those error codes here, please.

**Comment by Thomas-Smyth** [comment]
Neither I or the reporter can replicate this, so closing.
