### ISSUE TITLE
Butter & Cheese production

### ISSUE THREAD

**Issue by WilliamTheBear** [SmartPhoenix/Persistent-Kingdoms#622]
### Task Description
Butter & Cheese production
### Specification/Explicit TODO
Butter & Cheese production (will be one of those highlights in 2.0 changelog for the memes).

**Comment by WilliamPhoenix** [comment]
**Milk production**: Hitting a full-grown cow with an "Empty bucket" -> Get "Milk bucket".
**Butter production**: Having a "Milk bucket" in hands and hold F on "Butter churn" creating "Butter" and "Empty bucket"
**Cheese production**:  TBA

**Models:**
- Empty bucket: Exists.
- Milk bucket: Create from an empty bucket.
- Butter churn: Create it (example: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ma%C5%9Bniczka.svg/220px-Ma%C5%9Bniczka.svg.png)
- Butter: Exists in native.

**Comment by WilliamPhoenix** [comment]
**Required Models:**
- Empty bucket: Exists.
- Milk bucket: Create from an empty bucket.
- Butter churn: Create it ([example](https://c8.alamy.com/comp/E631WA/an-antique-wooden-butter-churn-E631WA.jpg))
- Butter: Exists in native.
- Curd bucket: Create from an empty bucket.
- Cooking stations: Exist.
- Pressing station: Create it ([example](https://i.pinimg.com/236x/da/75/3f/da753f3419127b8156134f0f0298e12f--cheese-press-wine-press.jpg))
- Cheese wheel: Exists.

**Comment by WilliamPhoenix** [comment]
Consumption:
Cheese wheel: Serve at a serving table - divides into 4 equal pieces. Then you can eat it.
Butter: Serve at a serving table - divide into 4 small butter bots. Then you can eat it.
